/*-----------------------------------------------------------------------------
      Name: Init_script
      Generated By: This is an auto generated script. You can, however, make a copy of this script using advanced script manager and enhance it.
      Date of generation: 12/04/2023 06:13:14
      Flow details:
      Build details: 4.11.0 build# 121
      Modification History:
  -----------------------------------------------------------------------------*/
  
      #include <stdio.h>
      #include <stdlib.h>
      #include <string.h>
      #include "ns_string.h"
  
      int init_script()
      {
         return 0;
      }
